//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:aseXML:r32")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:aseXML:r32", IsNullable=false)]
public partial class aseXML {

    private aseXMLHeader headerField;
    private aseXMLTransactions transactionsField;
    //private List<object> itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Header", typeof(aseXMLHeader), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public aseXMLHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }

[System.Xml.Serialization.XmlElementAttribute("Transactions", typeof(aseXMLTransactions), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public aseXMLTransactions Transactions {
        get {
            return this.transactionsField;
        }
        set {
            this.transactionsField = value;
        }
    }
    //public aseXMLHeader Items {
    //    get {
    //        return this.itemsField;
    //    }
    //    set {
    //        this.itemsField = value;
    //    }
    //}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class aseXMLHeader {
    
    private string fromField;
    
    private string toField;
    
    private string messageIDField;
    
    private string messageDateField;
    
    private string transactionGroupField;
    
    private string priorityField;
    
    private string marketField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string To {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageDate {
        get {
            return this.messageDateField;
        }
        set {
            this.messageDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionGroup {
        get {
            return this.transactionGroupField;
        }
        set {
            this.transactionGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Market {
        get {
            return this.marketField;
        }
        set {
            this.marketField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class aseXMLTransactions {
    
    private List<aseXMLTransactionsTransaction> transactionField;

    public aseXMLTransactions()
    {
        transactionField = new List<aseXMLTransactionsTransaction>();
        Transaction = transactionField;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transaction", typeof(aseXMLTransactionsTransaction), Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<aseXMLTransactionsTransaction> Transaction {
        get {
            return this.transactionField;
        }
        set {
            this.transactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class aseXMLTransactionsTransaction {

    public List<aseXMLTransactionsTransactionMeterDataNotification> meterDataNotificationField;
    
    private string transactionDateField;
    
    private string transactionIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeterDataNotification", typeof(aseXMLTransactionsTransactionMeterDataNotification) , Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<aseXMLTransactionsTransactionMeterDataNotification> MeterDataNotification {
        get {
            return this.meterDataNotificationField;
        }
        set {
            this.meterDataNotificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transactionDate {
        get {
            return this.transactionDateField;
        }
        set {
            this.transactionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transactionID {
        get {
            return this.transactionIDField;
        }
        set {
            this.transactionIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class aseXMLTransactionsTransactionMeterDataNotification {
    
    private string cSVIntervalDataField;
    
    private List<aseXMLTransactionsTransactionMeterDataNotificationParticipantRole> participantRoleField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CSVIntervalData {
        get {
            return this.cSVIntervalDataField;
        }
        set {
            this.cSVIntervalDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ParticipantRole", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<aseXMLTransactionsTransactionMeterDataNotificationParticipantRole> ParticipantRole {
        get {
            return this.participantRoleField;
        }
        set {
            this.participantRoleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class aseXMLTransactionsTransactionMeterDataNotificationParticipantRole {
    
    private string roleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
}
